# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

# windowrulev2 = rounding 0, title:(RMC2 I/O Simulator)
# windowrulev2 = noborder, title:(RMC2 I/O Simulator)
# windowrulev2 = noshadow, title:(RMC2 I/O Simulator)
# windowrulev2 = noblur, title:(RMC2 I/O Simulator)
# windowrulev2 = bordercolor rgb(ffffff) rgb(888888), title:(RMC2 I/O Simulator)
#
# windowrulev2 = noborder, title:(RMC2 I/O Simulator)
# windowrulev2 = noshadow, title:(RMC2 I/O Simulator)
# windowrulev2 = noblur, title:(RMC2 I/O Simulator)
# windowrulev2 = rounding 0, title:(RMC2 I/O Simulator)
# windowrulev2 = opacity 1.0 override, title:(RMC2 I/O Simulator)
# windowrulev2 = nodim, title:(RMC2 I/O Simulator)
# windowrulev2 = noanim, title:(RMC2 I/O Simulator)

windowrulev2 = float, title:(RMC2 I/O Simulator)
windowrulev2 = move 14 38, title:(RMC2 I/O Simulator)
windowrulev2 = size 716 238, title:(RMC2 I/O Simulator)

windowrulev2 = float, title:(RMC2 Platform)
windowrulev2 = move 280 108, title:(RMC2 Platform)
windowrulev2 = size 865 743, title:(RMC2 Platform)

windowrulev2 = float, initialClass:(Godot)
windowrulev2 = move 921 54, initialClass:(Godot)
windowrulev2 = size 480 820, initialClass:(Godot)
